baseURL = 'http://errickson.net/blog'
languageCode = 'en-us'
title = 'Josh Errickson'
publishDir = 'docs'
pygmentsOptions = "linenos=table"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true